Update website

diff --git a/doc/examples/update-website b/doc/examples/update-website
--- a/doc/examples/update-website
+++ b/doc/examples/update-website
@@ -22,11 +22,20 @@ run: expand=True
     sos convert {_input:a} {_output:a}  --template {_depends}
 
 [rerun]
-parameter: notebook = str
+parameter: notebook = ''
 
-input: f'../src/user_guide/{notebook}*.ipynb'
-run: expand=True
-    papermill --engine sos {_input} {_input:bn}_rerun.ipynb  --cwd {_input:d}
+input: f'../src/user_guide/{notebook}*.ipynb', group_by=1
+output: dynamic(f'{_input:bn}*')
+sh: expand=True
+    papermill --engine sos {_input} {_input:bn}.ipynb  --cwd {_input:d}
+    if [ $? -eq 0 ]; then
+        rm -f {_input:bn}.ipynb.failed
+        python remove_papermill_metadata.py {_input}
+        python remove_papermill_metadata.py {_input:bn}.ipynb
+    else
+        touch {_input:bn}.ipynb.failed
+        echo "\033[91mCould not convert notebook {_input}\033[0m"
+    fi
 
 
 [convert-guide]
